version: '3'
services:
  backend:
    image: vansh41104/djangoreact-backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: vansh41104/djangoreact-frontend
    ports:
      - "5174:5174"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  db:
    image: vansh41104/djangoreact-postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6104
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
