version: '3'
services:
  backend:
    build:
      context: ./backend/notes
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/notes:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./frontend/frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6104
    ports:
      - "5433:5432"  # Use host port 5433 instead of 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
